In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)      # empty matrix
print(x)


tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])


In [3]:
x = torch.rand(5, 3)               #  随机生成的 5 x 3 矩阵
print(x)

tensor([[0.9846, 0.5608, 1.0000],
        [0.3731, 0.8131, 0.6552],
        [0.2720, 0.1270, 0.7731],
        [0.1218, 0.9849, 0.4441],
        [0.8630, 0.3543, 0.8591]])


In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)    # 0 矩阵
print(x)

In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7571, -1.5918,  0.8835],
        [ 0.1870,  1.1656, -0.8476],
        [ 0.4493, -0.7927,  0.4817],
        [-0.9289, -0.8972, -0.1415],
        [-0.2363,  0.5440,  0.0825]])


In [6]:
print(x.size())

torch.Size([5, 3])


In [4]:
x = torch.randn(3,3)
print(x)
a,b = torch.max(x,0)
print(a)
print(b)

tensor([[ 0.9311, -1.6633, -0.0975],
        [-0.2741, -0.5782,  1.2035],
        [ 0.8413, -1.9369, -0.8146]])
tensor([ 0.9311, -0.5782,  1.2035])
tensor([0, 1, 1])


In [2]:
a = torch.randn(5,5,1)
b = torch.randn(5,5)

print((a+b).shape)

torch.Size([5, 5, 5])


In [5]:
a = torch.randn(2,3)
print(a)
print(a.shape)
a = a.squeeze()
print(a)
print(a.shape)


tensor([[-1.4933,  0.8688,  0.0590],
        [ 1.0817,  0.3852,  1.9667]])
torch.Size([2, 3])
tensor([[-1.4933,  0.8688,  0.0590],
        [ 1.0817,  0.3852,  1.9667]])
torch.Size([2, 3])
