In [1]:
import torch

In [39]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [40]:
y = x + 2    # 每个元素后面都加上
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [41]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [42]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [43]:
  # backprop
out.backward()
print(x.grad)     #  对 x 求 梯度  d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [44]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-203.1638,  751.3751, -790.2905], grad_fn=<MulBackward0>)


In [57]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
batch1.requires_grad_(True)
batch2.requires_grad_(True)
print(batch1.shape)
print(batch2.shape)
res = torch.bmm(batch1, batch2)
print(res)
# x = torch.tensor([3,3,3])
# y = torch.tensor([[1,2,3],[3,4,3]])
# print(x.shape)
# print(y.shape)
# z = torch.mm(x,y)
# print(z)
grad_tensor = torch.ones(10,3,5)
res.backward(grad_tensor)

torch.Size([10, 3, 4])
torch.Size([10, 4, 5])
tensor([[[-8.4431e-01,  2.4942e+00,  1.5517e+00, -3.2884e+00, -7.5976e-01],
         [ 7.3478e-02, -9.2005e-01, -1.7234e+00,  1.7148e+00,  1.5269e+00],
         [-4.9098e-01,  1.8992e+00,  8.5160e-02,  9.1001e-01,  6.0781e-01]],

        [[-1.5911e+00, -5.5965e-01,  8.0110e-01,  1.7565e+00,  7.7422e-01],
         [-2.2625e+00, -4.6642e+00,  1.3780e+00, -2.7596e+00,  2.1596e+00],
         [-2.1674e+00, -2.2215e-01,  8.6849e-01,  1.8657e+00,  3.3883e+00]],

        [[ 6.7001e+00,  1.2981e+00,  4.4339e+00, -1.0102e+00, -3.4357e+00],
         [-1.1019e+00, -1.1270e+00, -4.3272e-01,  3.4398e-01,  1.9397e+00],
         [-9.2975e-01,  1.8256e+00, -3.6584e-01, -1.2278e+00, -3.2544e+00]],

        [[ 8.4463e-01,  7.4221e-01,  1.2989e+00,  3.6386e-01, -6.5071e-01],
         [-1.3381e+00, -1.3566e+00,  2.3092e-01,  8.0266e-01,  1.9595e-03],
         [-1.4993e+00,  6.8853e-01,  1.4760e+00,  1.0831e+00, -1.8837e-01]],

        [[-2.4909e+00, -6.8046e+00

In [6]:
x = torch.randn(3,3,3)
print(x)
x = x[:,:,-1]
print(x)

tensor([[[-0.0757,  0.3318,  0.5485],
         [-0.4240, -0.8439,  0.2603],
         [-0.0914, -0.1799,  0.6055]],

        [[ 0.2746,  0.7052,  0.7522],
         [ 1.7225, -0.4954,  0.5483],
         [ 0.1778, -0.4291,  2.0804]],

        [[ 0.6068, -0.3127, -0.3094],
         [ 0.4608, -0.9867,  1.6668],
         [ 0.5965,  1.0938, -0.7315]]])
tensor([[ 0.5485,  0.2603,  0.6055],
        [ 0.7522,  0.5483,  2.0804],
        [-0.3094,  1.6668, -0.7315]])
